version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.codacy:codacy-coverage-reporter
    versions:
    - ">= 6.0.0-nativebinary.a"
    - "< 6.0.1"
  - dependency-name: org.apache.maven:maven-artifact
    versions:
    - "> 3.3.9"
  - dependency-name: org.apache.maven:maven-compat
    versions:
    - "> 3.3.9"
  - dependency-name: org.apache.maven:maven-core
    versions:
    - "> 3.3.9"
  - dependency-name: org.apache.maven:maven-plugin-api
    versions:
    - "> 3.3.9"
  - dependency-name: org.apache.maven.plugins:maven-compiler-plugin
    versions:
    - "> 3.8.0"
